---
firewalld_default_zone: internal

firewalld_enabled: yes

firewalld_exposed_ports:
  - 10000/tcp

firewalld_exposed_services:
  - ssh

firewalld_default_zone_networks:
  ## localhost
  - 127.0.0.0/8
  ## docker
  - 172.0.0.0/8
  - 10.0.0.0/8
  ## internal networks
  - 192.168.0.0/16
