---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: quarterly
  skip:
    - local-ansible-lint

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: ^(roles|playbooks|inventory|vars)/
        exclude: \.(ldif|schema)(\.j2)?$
      - id: end-of-file-fixer
        files: ^(roles|playbooks|inventory|vars)/
        exclude: \.(ldif|schema)(\.j2)?$
      - id: check-json
        files: ^(roles|playbooks|inventory|vars)/
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
        files: ^(roles|playbooks|inventory|vars)/
        exclude: |
          (?x)^(
              inventory/README\.md|
              vars/README\.md|
              plugins/modules/x509_certificate_verify\.py|
              roles/bootstrap_docker_stack/files/openvpn/nordvpn\.udp\.ovpn
          )$
      - id: mixed-line-ending
        files: ^(roles|playbooks|inventory|vars)/
        exclude: \.(ldif|schema)(\.j2)?$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        entry: |
          python3 -c "import locale;
          locale.setlocale = lambda *args: 'C.UTF-8';
          import yamllint.cli;
          yamllint.cli.run()"
        name: Lint YAML Files (yamllint)
        args: [-c=.yamllint]
        files: ^(roles|playbooks|inventory|vars)/
        language: python
        language_version: python3
        additional_dependencies: []

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Check Shell Scripts (shellcheck)
        files: ^(inventory)/
#        files: ^(roles|playbooks|inventory|vars)/
        types: [shell]

  - repo: local
    hooks:
      - id: verify-inventory
        name: Verify Ansible Inventory
        entry: python3 verify_inventory.py test -p
#        entry: python3 verify_inventory.py
        language: python
        language_version: python3
        additional_dependencies:
          - ansible-core
          - ruamel.yaml
          - PyYAML
          - pytest
          - pytest-shell-utilities
        pass_filenames: false
#        stages: [pre-commit, manual]

  - repo: local
    hooks:
      - id: local-ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: python
        files: ^(roles|playbooks|inventory|vars)/
        #        pass_filenames: true
        language_version: python3
        additional_dependencies:
          - ansible-lint==26.4.0
          - ansible-core>=2.16.0
          # required for collection MANIFEST handling
          - distlib
        stages: [pre-push]
