---
envs:
  - "PROD"
  - "QA"
  - "DEV"

global_xenv_group_file: "xenv_groups.yml"
global_xenv_hosts_file: "xenv_hosts.yml"

inventory_yml_list:
  - "hosts.yml"
  - "xenv_hosts.yml"
  - "xenv_groups.yml"

mutually_exclusive_group_patterns:
  - "docker_stack_env_(admin|dev|prod|qa)$"
  - "ca_domain_.*_(int_dettonville|int_johnson)$"
