---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Setup Cloudstack Manager
  include: setup.yml

- block:

  - name: Setup Cloudstack Manager
    include: initialize-api-config.yml
    tags:
      - cmconfig-api

  - name: Configure Cloudstack Manager
    include: configure.yml
#    environment:
#      CLOUDSTACK_KEY: "{{ cloudstack_api_key }}"
  tags:
    - cmconfig
