---

ansible_ping_test__module: ping
ansible_ping_test__fallback_to_cli: false

# determine if the role should fail the play for newly offline nodes
ansible_ping_test__fail_when_discovered_offline: true
