---

#ansible_host: "192.168.0.135"

ipv4_address: 192.168.0.135
ipv4_net_prefix: 16

docker_stack_service_route_name: "media"

#bootstrap_firewalld_exposed_ports:
#  - 10000/tcp
#
#firewalld_exposed_ports:
#  - 10000/tcp

firewalld_default_enable_source_port_53: yes

nfs_exports:
  - "/export      *(rw,fsid=0,async,nohide,no_root_squash,no_subtree_check,crossmnt)"
  - "/export/media         192.168.0.0/255.255.0.0(rw,async,nohide,no_subtree_check)"

#common_config__network:
#  network:
#    version: 2
#    renderer: networkd
#    ethernets:
#      eno1:
#        dhcp4: no
#        dhcp6: no
##        addresses: [192.168.0.135/16, ]
#        addresses:
#          - "{{ ipv4_address }}/{{ ipv4_net_prefix }}"
#        gateway4: "{{ internal_gateway_ip }}"
#        nameservers:
#          addresses: [192.168.0.1]


node_mounts:
  - name: "/tmp"
    src: "tmpfs"
    fstype: "tmpfs"
    ## ref: https://forums.plex.tv/t/guide-plex-media-server-with-intel-nuc-and-ubuntu-16-04-lts/217937
    options: 'size=100G,defaults,noatime,nosuid,nodev,mode=1777'

  - name: "/data"
#    src: "control01.johnson.int:/srv/data1/data"
    src: "control01.johnson.int:/data"
    fstype: "nfs"
    options: "intr,_netdev"

#  - name: "/srv/media"
#    src: "control01.johnson.int:/srv/data2/data/media"
#    fstype: "nfs"
#    options: "intr,_netdev"

  - name: "/srv/media"
    src: "nas02.dettonville.int:/mnt/storage/media"
    fstype: "nfs"
    options: "intr,_netdev"

  - name: "/srv/media_control"
    src: "control01.johnson.int:/export/data/media"
    fstype: "nfs"
    options: "intr,_netdev"

#  - name: "/srv/media_nas2"
#    src: "nas02.johnson.int:/export/nfsdata4"
#    fstype: "nfs"
#    options: "intr,_netdev"
