---

bind_aliases:
  - nas2

vmware_node_info:
  os: ubuntu20
  disk_size: 20
  mem: 4096
  network_type: static

ipv4_address: 192.168.10.11
ipv4_net_prefix: 16

#ansible_host: "{{ ipv4_address }}"

### ref: https://netplan.io/examples/
#common_config__network:
#  network:
#    version: 2
#    renderer: networkd
#    ethernets:
#      ens192:
#        dhcp4: no
#        dhcp6: no
#        addresses:
#          - "{{ ipv4_address }}/{{ ipv4_net_prefix }}"
#        gateway4: "{{ internal_gateway_ip }}"
#        nameservers:
#          addresses: [192.168.0.1]


nfs_exports:
  - "/mnt/storage         192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,fsid=1)"
  - "/mnt/                 192.168.0.0/255.255.0.0(ro,no_subtree_check)"
#  - "/export/nfsdata1         192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
  - "/export/nfsdata2        192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
#  - "/export/nfsdata3        192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
  - "/export/nfsdata4        192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
#  - "/export/backups         192.168.0.0/255.255.0.0(ro,no_root_squash,no_subtree_check)"
#  - "/export      *(ro,crossmnt,no_subtree_check)"
  - "/export      *(ro,no_subtree_check)"


node_mounts:
  - name: "/export/nfsdata2"
#    src: "UUID=d91c2cda-893f-4707-813c-cf514dc0698d"
#    src: "/dev/disk/by-id/dm-name-vgnfs2-lvnfsdata"
    src: "/dev/vgnfs2/lvnfsdata"
    fstype: "ext4"
    options: "defaults,nodev"

  - name: "/export/nfsdata4"
    src: "/dev/vgnfs4/lvnfsdata"
    fstype: "ext4"
    options: "defaults,nodev"

  - name: "/tmp"
    src: "tmpfs"
    fstype: "tmpfs"
    options: 'size=512m,defaults,noatime,nosuid,nodev,mode=1777'
#    options: 'size=2G,defaults,noatime,nosuid,nodev,mode=1777'

#  - name: "/data"
#    src: "control01.johnson.int:/srv/data1/data"
#    fstype: "nfs"
#    options: "intr,_netdev"
#
#  - name: "/data/media"
#    src: "/mnt/storage/media"
#    fstype: none
#    options: "rw,bind"
#
#  - name: "/data/backups"
#    src: "control01.johnson.int:/srv/backups"
#    fstype: "nfs"
#    options: "ro,intr,_netdev"
#
#  - name: "/data/plexmedia"
#    src: "media01.johnson.int:/export/media"
#    fstype: "nfs"
#    options: "intr,_netdev"
#
#  - name: "/srv/backups_nas2"
#    src: "nas02.dettonville.int:/export/nfsdata2/backups"
#    fstype: "nfs"
##    options: "auto,nofail,noatime,nolock,intr,tcp"
#    options: "intr,_netdev"
#
#  - name: "/srv/media_control"
#    src: "control01.johnson.int:/srv/data1/data/media"
#    fstype: "nfs"
#    options: "intr,_netdev"


is_veeam_backup_server: yes

