---

vmware_node_info:
  os: ubuntu20
  disk_size: 20
  mem: 4096
  network_type: static

ipv4_address: 192.168.10.10
ipv4_net_prefix: 16

#ansible_host: "{{ ipv4_address }}"

### ref: https://netplan.io/examples/
#common_config__network:
#  network:
#    version: 2
#    renderer: networkd
#    ethernets:
#      ens192:
#        dhcp4: no
#        dhcp6: no
#        addresses:
#          - "{{ ipv4_address }}/{{ ipv4_net_prefix }}"
#        gateway4: "{{ internal_gateway_ip }}"
#        nameservers:
#          addresses: [192.168.0.1]


nfs_exports:
#  - "/export/nfsdata1         192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
  - "/export/nfsdata2        192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
#  - "/export/nfsdata3        192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
  - "/export/nfsdata4        192.168.0.0/255.255.0.0(rw,no_root_squash,no_subtree_check,async,insecure)"
#  - "/export/backups         192.168.0.0/255.255.0.0(ro,no_root_squash,no_subtree_check)"
#  - "/export      *(ro,crossmnt,no_subtree_check)"
  - "/export      *(ro,no_subtree_check)"


node_mounts:
  - name: "/tmp"
    src: "tmpfs"
    fstype: "tmpfs"
    options: 'size=512m,defaults,noatime,nosuid,nodev,mode=1777'
#    options: 'size=2G,defaults,noatime,nosuid,nodev,mode=1777'

#  - name: "/srv/backups_nas2"
#    src: "nas02.dettonville.int:/export/nfsdata2/backups"
#    fstype: "nfs"
##    options: "auto,nofail,noatime,nolock,intr,tcp"
#    options: "intr,_netdev"

  - name: "/data"
    src: "admin.dettonville.int:/srv/data1/data"
    fstype: "nfs"
    options: "intr,_netdev"

  - name: "/data/media"
    src: "admin.dettonville.int:/srv/data2/data/media"
    fstype: "nfs"
    options: "intr,_netdev"

  - name: "/data/backups"
    src: "admin.dettonville.int:/srv/backups"
    fstype: "nfs"
    options: "ro,intr,_netdev"

  - name: "/data/plexmedia"
    src: "media01.johnson.int:/export/media"
    fstype: "nfs"
    options: "intr,_netdev"


is_veeam_backup_server: yes

