all:
  children:
    ansible_localhost:
      hosts:
        localhost: {}
    control_host_primary_baremetal:
      hosts:
        localhost: {}
    host_offline:
      hosts:
        #        esx02: {}
        #        esx03: {}
        esx02-idrac: {}
        vesxi01: {}
        vesxi02: {}
    network_switch:
      hosts:
        powerconnect01: {}
    tower_control_host:
      hosts:
        localhost: {}
        #    vm_template:
        #      hosts:
        #        localhost: {}
    vmware_cluster_compute:
      hosts:
        esx02: {}
        esx03: {}
    vmware_cluster_management:
      hosts:
        esx00: {}
        esx01: {}
        esx10: {}
    vmware_control_host:
      hosts:
        localhost: {}
    vmware_vcenter:
      hosts:
        vcenter7: {}
