#!/bin/sh
### BEGIN INIT INFO
# Provides:          chkservices
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5 S
# Default-Stop:      0 1 6
# Short-Description: Checking services
# Description:       Check services and start when something stops
#
### END INIT INFO

FILE_PID=/var/run/chkservices.pid

stop_chkservices () {

    if [ -e "$FILE_PID" ]
    then
        echo "Stopping chkservices..."
        kill `cat "$FILE_PID"`
        rm "$FILE_PID"
    else
        echo "Chkservices is not running."
        exit 1
    fi
}

start_chkservices () {

    if [ -e "$FILE_PID" ]
    then
        echo "Chkservices is already running."
        exit 1
    else
        echo "Starting chkservices..."
        /usr/bin/chkservices
    fi
}

usage () {
 echo "Usage: $0 [ start | stop | restart ] "
}

case "$1" in
    start)
            start_chkservices
            ;;
    stop)
            stop_chkservices
            ;;
    restart)
            stop_chkservices
            start_chkservices
            ;;
    *)
            usage
            ;;
esac

