#!/bin/bash

set -e

ansible-playbook -i tests/hosts tests/test.yml --syntax-check
ansible-playbook -i tests/hosts tests/test.yml --connection=local -s
ansible-playbook -i tests/hosts tests/test.yml --connection=local -s \
	| grep -q 'changed=0.*failed=0' \
    && (echo 'Idempotence test: pass' && exit 0) \
    || (echo 'Idempotence test: fail' && exit 1)
