---

- name: "Install mergerfs tools"
  include: install-mergerfs-tools.yml

- name: "Configure mergerfs disks"
  include: config-mergerfs-disks.yml

#- name: "Configure telegraf fix"
#  include: config-telegraf-fix.yml
