---

__docker_stack_proxyspec__awx:
  http:
    routers:
      awx-rtr:
        rule: "Host(`awx.{{ docker_stack_internal_domain }}`)"
        entryPoints:
          - https
        service: awx-svc
    services:
      awx-svc:
        loadBalancer:
          servers:
            - url: "{{ __docker_stack_proxyspec__awx_backend }}"

docker_stack_proxyspec__awx:
  proxy_config: "{{ __docker_stack_proxyspec__awx | d({}) }}"
