---
internal_root_domain: "johnson.local"
ca_domain: "{{ internal_root_domain }}"

#ca_commonName: "ca.johnson.local"
#ca_domainName: "johnson.local"
#ca_signerName: "{{ ca_root_cn }}"
ca_country: US
ca_state: "New York"
ca_locality: "CSH"
ca_organization: "Johnsonville Internal"
ca_organizationalUnit: "Mostly Impractical"
ca_email: "admin@johnson.local"
