---

docker_stack__service_groups__openwebui:
  - openwebui

docker_stack__openwebui__ollama_port: "{{ bootstrap_llm_host__ollama_port }}"
docker_stack__openwebui__secret_key: "{{ vault__webui_secret_key }}"
