---

docker_stack__service_groups__plane:
  - plane

docker_stack__plane__db_password: "{{ vault__postgres_password }}"
docker_stack__plane__minio_password: "{{ vault__minio_password }}"
docker_stack__plane__secret_key: "{{ vault__plane_secret_key }}"
