---

#docker_stack__vllm__model: "Qwen/Qwen2.5-Coder-32B-Instruct-FP8"
#docker_stack__vllm__model: "Qwen/Qwen3-30B-A3B-FP8"
#docker_stack__vllm__model: "QuantTrio/Qwen3.8-27B-AWQ"
docker_stack__vllm__model: "Qwen/Qwen3.8-27B"

#docker_stack__vllm__max_model_len: 32768
docker_stack__vllm__max_model_len: 16384
# since plan is to run both vLLM and Ollama concurrently on gpu01
# ensure vLLM's --gpu-memory-utilization is capped (e.g., at 0.5 or 0.6)
# so it leaves unified RAM available for Ollama's instances
docker_stack__vllm__gpu_memory_utilization: "0.60"
docker_stack__vllm__reasoning_parser: "qwen3"
docker_stack__vllm__tool_call_parser: "qwen3_coder"

#docker_stack__vllm__quantization: "awq"
docker_stack__vllm__quantization: "fp8"

# Add vLLM to your base URLs (using internal container name and port)
docker_stack__openwebui__openai_api_base_url: "http://llama:8080/v1;http://vllm-coder:8000/v1"

# Match the keys to the respective slots (leave blank if llama-cpp doesn't use one)
docker_stack__openwebui__openai_api_key: "{{ vault__llama_api_key }};{{ vault__vllm_api_key }}"
