---

docker_stack__service_groups__openwebui:
  - openwebui

docker_stack__openwebui__secret_key: "{{ vault__webui_secret_key }}"

docker_stack__openwebui__openai_api_base_url: "{{ vault__llama_api_url }};{{ vault__vllm_api_url }}"
docker_stack__openwebui__openai_api_key: "{{ vault__llama_api_key }};{{ vault__vllm_api_key }}"
