---

docker_stack__service_groups__vllm:
  - vllm

docker_stack__vllm__api_key: "{{ vault__vllm_api_key }}"
docker_stack__vllm__container_models_dir: "/models"

bootstrap_llm_host__ensure_vllm_models: true
bootstrap_llm_host__vllm_api_url: "https://vllm.{{ docker_stack__internal_domain }}"
bootstrap_llm_host__vllm_api_key: "{{ vault__vllm_api_key }}"
bootstrap_llm_host__vllm_container_name: "vllm-coder"
bootstrap_llm_host__vllm_host_volume_path: "{{ docker_container_base_dir }}/vllm/models"
bootstrap_llm_host__vllm_container_models_dir: "/models"

#docker_stack__openwebui__openai_api_base_url: "{{ vault__vllm_api_url }}"
docker_stack__openwebui__openai_api_base_url: "http://vllm-coder:8000/v1"
docker_stack__openwebui__openai_api_key: "{{ vault__vllm_api_key }}"
