---

bootstrap_docker__swarm_leader_host: "{{ groups['docker_swarm_leader_admin'] | first }}"
docker_stack__swarm_leader_host: "{{ groups['docker_swarm_leader_admin'] | first }}"
bootstrap_docker__swarm_managers: "{{ groups['docker_swarm_leader_admin'] + groups['docker_swarm_manager_admin'] }}"

#docker_container_base_dir_nfs: "/data/home/cluster-admin01/docker"
docker_container_base_dir_nfs: "/data/home/container-user/docker/{{
  docker_stack__environment }}/{{ docker_stack__service_route_name }}"

bootstrap_linux_mount__list__admin:
  - name: "{{ docker_container_base_dir }}"
    src: "{{ docker_container_base_dir_nfs }}"
    fstype: none
    options: "bind,nofail,_netdev"
#    options: "rw,auto,bind"

## cat /etc/fstab should contain:
#/data/home/cluster-admin01/docker /home/container-user/docker none bind 0 0
