---

docker_stack__service_groups__vllm:
  - vllm

docker_stack__vllm__api_key: "{{ vault__vllm_api_key }}"

docker_stack__vllm__vikunja_agent_api_token: "{{ vault__vikunja_agent_api_token }}"

docker_stack__vllm__vikunja_agent_secret_key: "{{ vault__vikunja_jwt_secret }}"
