---

docker_stack_services:
  - netbootxyz
  - jenkins
#  - mariadb
#  - fog

docker_stack_netbootxyz_root_dir: "/export/data/netbootxyz"
docker_stack_netbootxyz_config_dir: "{{ docker_stack_netbootxyz_root_dir }}/config"
docker_stack_netbootxyz_assets_dir: "{{ docker_stack_netbootxyz_root_dir }}/assets"

pxe_root_dir: "{{ docker_stack_netbootxyz_root_dir }}"
pxe_config_dir: "{{ docker_stack_netbootxyz_config_dir }}"
pxe_assets_dir: "{{ docker_stack_netbootxyz_assets_dir }}"

#kickstart_tftpdir: /var/lib/tftpboot
kickstart_tftpdir: "{{ pxe_config_dir }}/menus"


##node_mounts: []
#node_mounts:
#  - name: "/tmp"
#    src: "tmpfs"
#    fstype: "tmpfs"
##    opts: 'size=2048m'
##    options: 'size=512m,defaults,noatime,nosuid,nodev,mode=1777'
#    options: 'size=1G,defaults,noatime,nosuid,nodev,mode=1777'
#
#  - name: "/data"
#    src: "admin2.johnson.int:/data1/data"
#    fstype: "nfs"
#    options: "intr,_netdev"
#
#  ## to mount iso using fstab
#  ## ref: https://itekblog.com/mount-iso-using-fstab/
#  ##
#  #/path/to/file.iso /path/to/folder iso9660 loop 0 0
#  #/export/data/netbootxyz/assets/pxe/ubuntu/20.04/ubuntu-20.04-live-server-amd64.iso /export/data/netbootxyz/assets/pxe/ubuntu/20.04/netboot iso9660 loop,ro,auto 0 0
##  - name: "/export/data/netbootxyz/assets/pxe/ubuntu/20.04/netboot"
#  - name: "/export/netboot"
#    src: "/export/data/netbootxyz/assets/pxe/ubuntu/20.04/ubuntu-20.04-live-server-amd64.iso"
#    fstype: "iso9660"
#    options: "loop,ro,auto 0 0"
#
#  #/export/data/netbootxyz/assets/pxe/ubuntu/20.04/netboot/ /export/netboot/ bind rw,bind 0 0
#  - name: "/export/data/netbootxyz/assets/pxe/ubuntu/20.04/netboot/"
#    src: "/export/netboot/"
#    fstype: "bind"
#    options: "rw,bind 0 0"
#
#nfs_exports:
#  - "/srv      192.168.0.0/255.255.0.0(ro,fsid=0,async,nohide,no_subtree_check,crossmnt)"
#  - "/export/netboot 192.168.0.0/255.255.0.0(ro,nohide)"
