---

docker_stack__subdomain: ''

docker_stack__internal_root_domain: "{{ (docker_stack__subdomain | d('', true) | length > 0)
  | ternary(docker_stack__subdomain + '.' + service_route_internal_root_domain,
  service_route_internal_root_domain) }}"

docker_stack__environment: "test"

#docker_container_base_dir_nfs: "/data/home/cluster-admin01/docker"
docker_container_base_dir_nfs: "/data/home/container-user/docker/{{
  docker_stack__environment }}/{{ docker_stack__service_route_name }}"
