---

docker_stack__service_groups__vllm:
  - vllm

docker_stack__vllm__api_key: "{{ vault__vllm_api_key }}"

docker_stack__vllm__vikunja_agent_api_token: "{{ vault__vikunja_agent_api_token }}"

docker_stack__vllm__vikunja_agent_secret_key: "{{ vault__vikunja_jwt_secret }}"

# Add vLLM to your base URLs (using internal container name and port)
docker_stack__openwebui__openai_api_base_url: "http://llama:8080/v1;http://vllm-coder:8000/v1"

# Match the keys to the respective slots (leave blank if llama-cpp doesn't use one)
docker_stack__openwebui__openai_api_key: ";{{ vault__webui_secret_key }}"
