---

docker_stack__service_groups__repo_proxy:
  - repo_proxy

bootstrap_linux_package__use_repo_proxy: false

docker_stack__repo_proxy__mirrors:
  ubuntu: ""
  ubuntu_ports: ""
  debian: ""
  debian_security: ""
  centos: ""
  alpine: ""
  docker-ce: ""
  webmin: ""

docker_stack__repo_proxy__passthrough_list_custom:
  - download.docker.com
  - download.webmin.com
  - workbench.download.nvidia.com
  - developer.download.nvidia.com
  - repo.download.nvidia.com
  - nvidia.github.io
  - snapshot.ppa.launchpadcontent.net
  - pkgs.k8s.io
  - prod-cdn.packages.k8s.io
  - repo.plex.tv
