---

docker_stack__proxy_services:
  - awx
  - awx_orig
#  - wordpress
#  - nginx

### AWX
# awx_orig_enabled: false
awx_orig_enabled: true

docker_stack__awx_backend_port: "{{ awx_host_port }}"
docker_stack__awx_orig_backend_port: "{{ awx_orig_host_port }}"
