---

docker_stack__service_groups__llama:
  - llama

docker_stack__llama__secret_key: "{{ vault__webui_secret_key }}"
docker_stack__llama__api_key: "{{ vault__llama_api_key }}"

bootstrap_llm_host__install_llama: true
bootstrap_llm_host__llama_api_url: "https://llama.{{ docker_stack__internal_domain }}"
bootstrap_llm_host__llama_api_key: "{{ vault__llama_api_key }}"
bootstrap_llm_host__llama_container_name: "llama"
bootstrap_llm_host__llama_host_volume_path: "{{ docker_container_base_dir }}/llama/models"
