---

docker_stack__service_groups__openwebui:
  - openwebui

ollama_http_port: 11434

docker_stack__openwebui__secret_key: "{{ vault__webui_secret_key }}"

bootstrap_llm_host__ollama_port: "{{ ollama_http_port }}"
