---

bootstrap_gpu_drivers__nvidia_install_container_toolkit: true

## it is assumed that the machine running the ollama stack has at least 1 nvidia GPU
## override at the host_vars/machine_name.yml if more exist
bootstrap_docker__options__nvidia:
  default-runtime: "nvidia"
  node-generic-resources:
    - "NVIDIA-GPU=1"
  runtimes:
    nvidia:
      path: "nvidia-container-runtime"
      runtimeArgs: []
