---

docker_stack__service_groups__ollama:
  - ollama
  - openwebui

bootstrap_llm_host__ollama_user: "{{ docker_stack__user_username }}"
bootstrap_llm_host__ollama_runtime: "docker"
bootstrap_llm_host__ollama_container_name: "ollama"
bootstrap_llm_host__ollama_host_volume_path: "/home/container-user/docker/ollama/data"
# from docker-compose ps output, the prefix
bootstrap_llm_host__docker_compose_project_name: "docker"

llama_cppserver_http_port: 11432
ollama_http_port: 11434

docker_stack__ollama__http_port: "{{ ollama_http_port }}"
docker_stack__openwebui__ollama_port: "{{ ollama_http_port }}"
docker_stack__openwebui__secret_key: "{{ vault__webui_secret_key }}"

docker_stack__openwebui__openai_api_base_url: "http://gpu02.johnson.int:{{ llama_cppserver_http_port }}/v1"

# use the docker service name for ollama service
docker_stack__openwebui__ollama_host: ollama

bootstrap_llm_host__install_ollama: false
bootstrap_llm_host__install_open_webui: false
bootstrap_llm_host__configure_proxy: false
bootstrap_llm_host__configure_firewall: false

bootstrap_llm_host__ollama_port: "{{ ollama_http_port }}"

# optional pin
# bootstrap_gpu_drivers__nvidia_container_toolkit_version: "1.19.0-1"
