---

docker_stack__service_groups__kanban:
  - vikunja

docker_stack__vikunja__db_password: "{{ vault__postgres_password }}"
docker_stack__vikunja__jwt_secret: "{{ vault__vikunja_jwt_secret }}"

#docker_stack__vikunja__ldap_group_dn_default: "ou=groups,{{ docker_stack__ldap__base_dn }}"
docker_stack__vikunja__ldap_group_dn_default: "ou=vikunja,{{ docker_stack__ldap__application_groups_base_dn }}"
