---

#time_server: 0.pool.ntp.org
time_server: 192.168.0.1

#docker_stack_run_services: no
#docker_stack_traefik_version: v1
#docker_stack_traefik_certprovider_qa: yes

docker_stack_script_dir: "/opt/scripts"

docker_stack_enable_external_route: yes

docker_stack_external_domain: "{{ docker_stack_external_root_domain }}"

#docker_user_uid: 1006
#docker_user_gid: 1006

docker_stack_services:
  - healthchecks
  - registry
  - stepca
  - openldap
  - jenkins
  - postgres
  - keycloak
  - gitea
  - auth
  - samba
  - redis
  - grafana
  - netbootxyz
  - archiva
  - netbootxyz
#  - postfix
#  - jenkins
#  - samba
#  - mariadb
#  - fog
#  - bind
#  - cobbler

docker_stack_proxy_services:
  - awx
#  - nginx
  - wordpress

docker_stack_volumes:
#  prometheus: {}
#  grafana: {}
#  alertmanager: {}
#  bacula_pgdata: {}
  keycloak_data: {}

#docker_user_username: "container-user"
#docker_user_group: "container-user"

#external_domain: "{{ external_root_domain }}"
#docker_stack_external_domain: "{{ external_domain }}"
#
#registry_name: "{{ passthru_registry_name }}"
#docker_stack_registry_service_common_name: "{{ docker_stack_internal_domain }}"
#docker_stack_registry_users: "{{ registry_users }}"

docker_stack_archiva_http_port: 4080

docker_stack_wordpress_backend: "http://wordpress.johnson.int:80"

## JENKINS
docker_stack_jenkins_ldap_host: "{{ ldap_internal_host }}"
docker_stack_jenkins_ldap_base_dn: "{{ ldap_internal_base_dn }}"

#docker_stack_jenkins_image: "media.johnson.local:5000/jenkins-docker:latest"

docker_stack_jenkins_agent_image: "media.johnson.int:5000/jenkins-docker-cicd-agent:latest"
#docker_stack_jenkins_agent_jenkins_url: "https://jenkins.admin.johnson.int"
#docker_stack_jenkins_agent_tunnel: "jenkins.admin.johnson.int:9000"
docker_stack_jenkins_agent_jenkins_host: "jenkins.admin.johnson.int"
docker_stack_jenkins_agent_jenkins_url: "https://{{ docker_stack_jenkins_agent_jenkins_host }}"
docker_stack_jenkins_agent_tunnel: "{{ docker_stack_jenkins_agent_jenkins_host }}:9000"
docker_stack_jenkins_agent_workdir: "/home/jenkins/agent"
docker_stack_jenkins_agent_secret: "gogoggogogogogogogogoogg"

docker_stack_jenkins_swarm_image: "media.johnson.int:5000/jenkins-swarm-agent:latest"
docker_stack_jenkins_swarm_username: "{{ jenkins_agent_username }}"
docker_stack_jenkins_swarm_password: "{{ jenkins_agent_password }}"

docker_stack_keycloak_postgres_user: keycloak
docker_stack_keycloak_postgres_password: "password"

docker_stack_gitea_http_port: 3080
docker_stack_gitea_ssh_port: 2222
docker_stack_gitea_postgres_user: gitea
docker_stack_gitea_postgres_password: password

docker_stack_postgres_databases:
  - "{{ docker_stack_keycloak_postgres_user }},{{ docker_stack_keycloak_postgres_password }}"
  - "{{ docker_stack_gitea_postgres_user }},{{ docker_stack_gitea_postgres_password }}"


### LDAP
#ldap_server: "ldap.{{ ldap_internal.ldap_domain }}"
#ldap_host: "ldap.{{ ldap_internal.ldap_domain }}"
#ldap_uri: "ldap://{{ ldap_host }}/"
##ldap_uri: ldaps://ldap.johnson.int
#ldap_port: "389"
#
#ldap_base: dc=johnson,dc=int

## SAMBA
samba_data_path: /data
samba_server: samba.johnson.int
samba_mail_domain: dettonville.org

### AWX


### PXE

docker_stack_netbootxyz_root_dir: "/export/data/netbootxyz"
docker_stack_netbootxyz_config_dir: "{{ docker_stack_netbootxyz_root_dir }}/config"
docker_stack_netbootxyz_assets_dir: "{{ docker_stack_netbootxyz_root_dir }}/assets"

pxe_root_dir: "{{ docker_stack_netbootxyz_root_dir }}"
pxe_config_dir: "{{ docker_stack_netbootxyz_config_dir }}"
pxe_assets_dir: "{{ docker_stack_netbootxyz_assets_dir }}"

#kickstart_tftpdir: /var/lib/tftpboot
kickstart_tftpdir: "{{ pxe_config_dir }}/menus"
