---

docker_stack__service_groups__llama_cppserver:
  - llama_cppserver

bootstrap_gpu_drivers__nvidia_install_container_toolkit: true

## it is assumed that the machine running the ollama stack has at least 1 nvidia GPU
## override at the host_vars/machine_name.yml if more exist
bootstrap_docker__options:
  default-runtime: "nvidia"
  node-generic-resources:
    - "NVIDIA-GPU=1"
  runtimes:
    nvidia:
      path: "nvidia-container-runtime"
      runtimeArgs: []

llama_cppserver_http_port: 11432

docker_stack__llama_cppserver__http_port: "{{ llama_cppserver_http_port }}"

docker_stack__llama_cppserver__secret_key: "{{ vault__webui_secret_key }}"

bootstrap_llm_host__install_llama_cpp: true
bootstrap_llm_host__llama_cpp_port: "{{ llama_cppserver_http_port }}"
bootstrap_llm_host__llama_cpp_container_name: "llama-cpp"
