---

bootstrap_gpu_drivers__nvidia_install_container_toolkit: true

## it is assumed that the machine running the ollama stack has at least 1 nvidia GPU
## override at the host_vars/machine_name.yml if more exist
bootstrap_docker__options:
  default-runtime: "nvidia"
  node-generic-resources:
    - "NVIDIA-GPU=1"
  runtimes:
    nvidia:
      path: "nvidia-container-runtime"
      runtimeArgs: []

docker_stack__service_groups__ollama:
  - ollama
  - openwebui

docker_stack__ollama__ollama_port: "{{ bootstrap_llm_host__ollama_port }}"
docker_stack__ollama__secret_key: "{{ vault__webui_secret_key }}"

# use the docker service name for ollama service
docker_stack__openwebui__ollama_host: ollama

bootstrap_llm_host__install_ollama: false
bootstrap_llm_host__install_open_webui: false
bootstrap_llm_host__configure_proxy: false

# optional pin
# bootstrap_gpu_drivers__nvidia_container_toolkit_version: "1.19.0-1"
