---

# Add llama and vLLM to your base URLs (using internal container name and port)
#docker_stack__openwebui__openai_api_base_url: "{{ vault__llama_api_url }};{{ vault__vllm_api_url }}"
docker_stack__openwebui__openai_api_base_url: "http://llama:8080/v1;http://vllm-coder:8000/v1"

# Match the keys to the respective slots (leave blank if llama-cpp doesn't use one)
docker_stack__openwebui__openai_api_key: "{{ vault__llama_api_key }};{{ vault__vllm_api_key }}"
