---

docker_stack__service_groups__vllm:
  - vllm-vision

docker_stack__vllm_vision__api_key: "{{ vault__vllm_api_key }}"

#docker_stack__vllm_vision__max_model_len: 32768
docker_stack__vllm_vision__max_model_len: 16384

# When running two vLLM containers concurrently on the same physical GPU,
# their combined memory utilization must stay under 0.95 to avoid
# CUDA Out-Of-Memory errors during initial KV cache allocation
docker_stack__vllm_vision__gpu_memory_utilization: "0.35"
