---

docker_stack__service_groups__ollama:
  - ollama

docker_stack__ollama__container_home_dir: "/ollama"

bootstrap_llm_host__ollama_user: "{{ docker_stack__user_username }}"
bootstrap_llm_host__ollama_runtime: "docker"

bootstrap_llm_host__ollama_container_name: "ollama"
bootstrap_llm_host__ollama_container_home_dir: "{{ docker_stack__ollama__container_home_dir }}"

bootstrap_llm_host__ollama_host_volume_path: "/home/container-user/docker/ollama/data"

bootstrap_llm_host__ollama_api_url: "https://ollama.{{ docker_stack__internal_domain }}"
bootstrap_llm_host__ollama_api_key: "{{ vault__ollama_api_key }}"
bootstrap_llm_host__ollama_api_auth_type: "basic"

# use the docker service name for ollama service
docker_stack__openwebui__ollama_host: ollama
