---

docker_stack__service_groups__llm_agent:
  - llm_agent

docker_stack__llm_agent__llm_api_key: "{{ vault__vllm_api_key }}"

docker_stack__llm_agent__vikunja_endpoint: "kanban.admin.{{ service_route_internal_root_domain }}"
docker_stack__llm_agent__vikunja_agent_api_token: "{{
  vault__vikunja_agent_api[docker_stack__llm_agent__vikunja_endpoint].token }}"

docker_stack__llm_agent__vikunja_agent_secret_key: "{{ vault__vikunja_jwt_secret }}"

docker_stack__llm_agent__gitea_url: "{{ git_repo_url_base_https }}"
docker_stack__llm_agent__gitea_token: "{{
  vault__gitea__tokens[git_repo_endpoint]['llm_agent'] }}"
