---

#docker_stack__vllm__model: "Qwen/Qwen2.5-Coder-32B-Instruct-FP8"
#docker_stack__vllm__model: "Qwen/Qwen3-30B-A3B-FP8"
#docker_stack__vllm__model: "QuantTrio/Qwen3.8-27B-AWQ"
docker_stack__vllm__model: "Qwen/Qwen3.8-27B"

docker_stack__vllm__max_model_len: 16384
docker_stack__vllm__gpu_memory_utilization: "0.60"
docker_stack__vllm__reasoning_parser: "qwen3"
docker_stack__vllm__tool_call_parser: "qwen3_coder"

#docker_stack__vllm__quantization: "awq"
docker_stack__vllm__quantization: "fp8"
