---

docker_stack__service_groups__vllm_execution:
  - vllm_execution

docker_stack__vllm_execution__api_key: "{{ vault__vllm_api_key }}"
docker_stack__vllm_execution__container_models_dir: "/models"

run_vllm_benchmark_tests__runtime: "docker"
run_vllm_benchmark_tests__container_name: "vllm-execution"
run_vllm_benchmark_tests__service_name: "vllm-execution"

#run_vllm_benchmark_tests__model_name: "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-NVFP4"
run_vllm_benchmark_tests__model_name: "nemotron-lightning"
