---
bootstrap_llm_host__ollama_port: "11434"
## LLM proxy should listen on a port other than standard stack ports
bootstrap_llm_host__webui_port: "2080"
bootstrap_llm_host__proxy_port: "80"
bootstrap_llm_host__install_open_webui: true
bootstrap_llm_host__install_ollama_webui: false
bootstrap_llm_host__webui_secret_key: "{{ vault__webui_secret_key }}"

bootstrap_llm_host__llama_cpp_models:
  ## AUTOCOMPLETE MODEL
  # or Q4_K_M if you want lighter
  - repo: unsloth/gemma-4-E2B-it-GGUF
    filename: gemma-4-E2B-it-Q5_K_M.gguf
  ## Additional Large Model - Gemma 31B
  - repo: unsloth/gemma-4-31B-it-GGUF
    filename: gemma-4-31B-it-Q5_K_M.gguf

bootstrap_llm_host__models:
  - name: "deepseek-coder:6.7b"
  - name: "deepseek-coder:1.3b"
  - name: "deepseek-llm:7b"
  # ~17 GB VRAM at Q4_K_M, excellent coding/reasoning
  - name: "qwen3.5:27b"
  ## CHAT & EDIT MODEL
  - name: "qwen2.5-coder:32b"
  ## AUTOCOMPLETE MODEL
  - name: "qwen2.5-coder:1.5b"
#  - name: "qwen3-coder:32b"
  ## FOR QUICK LOCAL TASKS
  - name: "llama3.1:8b"
  - name: "nomic-embed-text"
  - name: "bona/bge-reranker-v2-m3"

firewalld_ports__llm:
  - "{{ bootstrap_llm_host__proxy_port }}/tcp"
  - "{{ bootstrap_llm_host__webui_port }}/tcp"
  - "{{ bootstrap_llm_host__ollama_port }}/tcp"
