---

## ref: https://github.com/geerlingguy/ansible-role-ntp

ntp_timezone: America/New_York

ntp_manage_config: true
ntp_restrict:
  - "192.168.0.1"

ntp_servers:
  - "192.168.0.1 prefer iburst"

ntp_tinker_panic: true
