---

bind_ipv4_address: "{{ ipv4_address }}"

## ref: https://netplan.io/examples/
common_config__network:
  network:
    version: 2
    renderer: networkd
    ethernets:
      ens192:
        dhcp4: no
        dhcp6: no
        addresses:
          - "{{ ipv4_address }}/{{ ipv4_net_prefix }}"
        gateway4: "{{ internal_gateway_ip }}"
        nameservers:
          addresses: [192.168.0.1]
#        set-name: ens192
