---

hostname_name_full: "{{ ansible_fqdn }}"
hostname_name_short: "{{ ansible_fqdn.split('.')[0] }}"

figurine_name: "{{ ansible_hostname }}"

cacert_keyring_host: "control01.johnson.int"

node_mounts:
  - name: "/data"
#    src: "control01.johnson.int:/srv/data1/data"
    src: "control01.johnson.int:/data"
    fstype: "nfs"
    options: "intr,_netdev"
