---

deploy_vm__vmware_vm_os_flavor: windows

internal_root_domain: johnson.int

# vmware_vm_image_os: win2012
# vmware_vm_image_os: win2016
deploy_vm__vmware_vm_guest_id: windows8srv-64

#os_build_user: packer
os_build_user: osbuild
