---

deploy_vm__vmware_vm_num_cpus: 4
deploy_vm__vmware_vm_disk_size_gb: 100
deploy_vm__vmware_vm_memory_mb: 16384
deploy_vm__vmware_vm_disk_type: thin

vmware_vm_host: "esx02"
deploy_vm__vmware_vm_host: "{{ vmware_vm_host }}.{{ deploy_vm__vmware_guest_domain }}"
deploy_vm__vmware_vm_datastore: "{{ vmware_vm_host }}_ds1"
